name: cellcharter
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - mamba
  - pip
  - python=3.10
  - jaxlib=*=*cuda*
  - jax=0.4.13
  - pytorch
  - pytorch-cuda=11.7
  - scvi-tools=0.20.3
  - pip:
    - ipywidgets
    - jupyterlab
    - cellcharter
    - pyro-ppl==1.8.6