name: deeplinc
channels:
dependencies:
  - pip
  - python=3.7
  - pip:
    - ipywidgets==8.0.4
    - jupyterlab==3.6.1
    - leidenalg==0.9.1
    - matplotlib==3.5.3
    - networkx==2.6.0
    - protobuf==3.20.0
    - seaborn==0.8.1
    - squidpy==1.2.2
    - tensorflow==1.13.1
    - umap-learn==0.5.3