name: nichecompass-reproducibility
channels:
  - bioconda
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - poetry=1.4.2
  - bedtools=2.30.0
  - pip:
    - ipykernel==6.15.3
    - ipywidgets==8.0.2
    - jupyterlab==3.4.7
    - GraphST==1.1.1
    - opencv-python==4.7.0.68
    - openpyxl==3.0.10
    - plottable==0.1.5
    - POT==0.8.2
    - scArches==0.5.7
    - tiledb==0.20.0
    - tiledbsoma==0.1.22