name: autotalker
channels:
  - bioconda
  - conda-forge
  - pytorch
dependencies:
  - cellrank-krylov=1.5.1
  - cudatoolkit=11.3.1
  - pip=22.2.2
  - python=3.9
  - pytorch=1.12.1
  - r-base=4.2.2
  - r-devtools=2.4.5
  - pip:
    - anndata2ri==1.1
    - bbknn==1.5.1
    - captum==0.6.0
    - GraphST==1.1.1
    - ipykernel==6.15.3
    - ipywidgets==8.0.2
    - jupyterlab==3.4.7
    # - scarches==0.5.6 needs to be updated to newer release once available
    # (until then install from source with python3 setup.py install)
    - mlflow==1.28.0
    - opencv-python==4.7.0.68
    - openpyxl==3.0.10
    - POT==0.8.2
    - pyreadr==0.4.6
    - rpy2==3.5.7
    - scib==1.1.1
    - scikit-misc==0.1.4
    - scvi-tools==0.19.0
    - squidpy==1.2.2
    - tiledb==0.20.0
    - tiledbsoma==0.1.22
    - torch-geometric==2.1.0.post1
    - torch-scatter==2.0.9
    - -f https://data.pyg.org/whl/torch-1.12.1+cu113.html
    - torch-sparse==0.6.15
    - -f https://data.pyg.org/whl/torch-1.12.1+cu113.html